api:
  build: ./api
  links:
   - db
  ports:
   - "3001:3001"
  environment:
   - NODE_ENV=development
client:
  build: ./client
  links:
   - api
  ports:
   - "3000:3000"
  environment:
   - NODE_ENV=development
db:
  image: mongo
  ports:
   - "27017:27017"
db-seed:
  build: ./db-seed
  links:
   - db
